Ecom/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from ecommerce import views
from accounts.views import login_page,register_page,logout_view
from carts.views import cart_home,cart_update,checkout_home,checkout_done
from addresses.views import checkout_address_create_view


urlpatterns = [
    path('admin/', admin.site.urls),
path('',views.home,name='homepage' ),
# re_path('^contact/$',views.contact,name='contact' ),
re_path('^cart/$',cart_home,name='cart' ),
re_path('^checkout/$',checkout_home,name='checkout'),
path('checkout/address/create',checkout_address_create_view,name='checkout_address_create'),
re_path('^update/$',cart_update,name='cartupdate'),
re_path('^about/$',views.about,name='about' ),
re_path('^login/$',login_page,name='login' ),
re_path('^logout/$',logout_view,name='logout' ),
re_path('^register/$',register_page,name='register' ),
re_path('^checkout/success$',checkout_done,name='success'),
path('products/',include(('products.urls','products'),namespace='products')),
path('search/',include(('search.urls','search'),namespace='search')),
path('my_orders/',include(('orders.urls','orders'),namespace='orders')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path,re_path

from . import views

urlpatterns = [
    re_path('^$', views.myorders, name='myorders'),
    path('<slug:pk>/', views.OrderDetailView.as_view(), name='orderdetail')

]

products/urls.py
from django.urls import path,re_path

from . import views

urlpatterns = [
    re_path('^$', views.ProductListView.as_view(), name='productlist'),
    path('<slug:pk>/', views.ProductDetailView.as_view(), name='productdetail')
]

search/urls.py
from django.urls import path,include,re_path
from .views import SearchListView
from products import views
urlpatterns = [
#path('',views.home,name='searchlist' ),
path('<slug:pk>',views.ProductDetailView.as_view(), name='search_product_detail'),
re_path('^$', SearchListView.as_view(), name='search_list'),
]

templates/about.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
     {% include 'navbar.html' %}
<div class="text-center"> <h1 >{{ title }}</h1></div>
    <hr/>
    <b>This Page is under Construction !!</b>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
      {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      {% include 'css.html' %}
    <title>{{ title }}</title>
  </head>
  <body>
<div class="container">
    {% block content %}

  {% endblock %}
</div>

{% include 'js.html' %}


  </body>
</html>

templates/css.html
    <!-- Bootstrap CSS -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
     {% include 'navbar.html' %}
<div class="text-center"> <h1 >{{ title }}</h1></div>


        <div class="row">
{#            <div class="col">#}
{#                {{ content }}#}
{#            </div>#}
        </div>
        {% if request.user.is_authenticated %}
             <hr/>
            <div class=" text-center">
             <p>{{ premium }}</p>
                <br><a href="{% url 'products:productlist' %}"><img src="{% static "images/cart.jpg" %}" class="img-fluid"/></a>
                <p>Fill your cart</p>
            <p>This site is developed by Rahul Jain.</p>
            <p>This is a sample ecommerce site. </p>
                <p>This site should not be used for commercial purpose without the permission of owner</p>
            <p>Chekout my site and Enjoy !!</p>
            </div>
        {% else %}
    <hr/>
     <div class="text-center">
         <br><a href="{% url 'products:productlist' %}"><img src="{% static "images/images.jpg" %}" class="img-fluid"/></a>
            <p>This site is developed by Rahul Jain.</p>
            <p>This is a sample ecommerce site. </p>
          <p>This site should not be used for commercial purpose without the permission of owner</p>
            <p>Chekout my site and Enjoy !!</p>
            </div>
        {% endif %}









{#                <div class="col-sm-6 col-12">#}
{#                    {% if form %}#}
{#                    <form method="post">#}
{#                        {% csrf_token %}#}
{#                       {{ form }}#}
{#                        <button type="submit" class="btn btn-default">Submit</button>#}
{#                    </form>#}
{#                    {% endif %}#}
{##}
{#                </div>#}

    {% endblock %}

templates/js.html
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      {% load staticfiles %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>

templates/navbar.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
   <div class='container'>
      <a class="navbar-brand" href="{% url 'homepage' %}">
        <img src="{% static 'images/icon.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        JKart
      </a>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarCollapseLinks' aria-expanded='false' aria-label='Toggle Navigation'>
        <span class='navbar-toggler-icon'></span>
      </button>




      <div class='collapse navbar-collapse' id='navbarCollapseLinks'>
        <ul class='navbar-nav'>
          <li class='nav-item'>
            <a href='{% url 'homepage' %}' class='nav-link'>Home</a>
          </li>
          <li class='nav-item'>
            <a href='{% url 'about' %}' class='nav-link'>About</a>
          </li>
          <li class='nav-item'>
            <a href='{% url 'products:productlist' %}' class='nav-link'>Products</a>
          </li>
                    {% if request.user.is_authenticated %}

             <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
            {% else %}
             <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
        {% endif %}
          <li class="nav-item">
        <a class="nav-link" href="{% url 'cart' %}">{{ request.session.cart_items }}<i class="fas fa-shopping-cart"></i></a>
      </li>

        </ul>

        <form class="form-inline ml-auto" action="{% url 'search:search_list' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      {% if request.user.is_authenticated %}
           <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> {{ request.user.username }} <span class="caret"></span></a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'orders:myorders' %}">My Orders</a>
              <a class="dropdown-item" href="{% url 'cart' %}">My Cart</a>
            </div>
        </li>
      </ul>

      {% endif %}
      </div>
  </div>
</nav>
{% endblock %}






{#{% extends 'base.html' %}#}
{#{% block content %}#}
{#<nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#  <a class="navbar-brand" href="{% url 'homepage' %}">JKart</a>#}
{#  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#    <span class="navbar-toggler-icon"></span>#}
{#  </button>#}
{##}
{#  <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#    <ul class="navbar-nav mr-auto">#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'about' %}">About</a>#}
{#      </li>#}
{#        <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'products:productlist' %}">Products</a>#}
{#      </li>#}
{#    <li class="nav-item">#}
{#        <a class="nav-link " href="{% url 'contact' %}">Contact</a>#}
{#      </li>#}
{#        {% if request.user.is_authenticated %}#}
{##}
{#             <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'logout' %}">Logout</a>#}
{#      </li>#}
{#            {% else %}#}
{#             <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'register' %}">Register</a>#}
{#      </li>#}
{#        <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'login' %}">Login</a>#}
{#      </li>#}
{#        {% endif %}#}
{#      <li class="nav-item dropdown disabled">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="{% url 'products:productlist' %}">Products</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{##}
{#    </ul>#}
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
{#  </div>#}
{#</nav>#}
{#{% endblock %}#}