Ecom/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from ecommerce import views
from accounts.views import login_page,register_page,logout_view
from carts.views import cart_home,cart_update,checkout_home,checkout_done
from addresses.views import checkout_address_create_view


urlpatterns = [
    path('admin/', admin.site.urls),
path('',views.home,name='homepage' ),
# re_path('^contact/$',views.contact,name='contact' ),
re_path('^cart/$',cart_home,name='cart' ),
re_path('^checkout/$',checkout_home,name='checkout'),
path('checkout/address/create',checkout_address_create_view,name='checkout_address_create'),
re_path('^update/$',cart_update,name='cartupdate'),
re_path('^about/$',views.about,name='about' ),
re_path('^login/$',login_page,name='login' ),
re_path('^logout/$',logout_view,name='logout' ),
re_path('^register/$',register_page,name='register' ),
re_path('^checkout/success$',checkout_done,name='success'),
path('products/',include(('products.urls','products'),namespace='products')),
path('search/',include(('search.urls','search'),namespace='search')),
path('my_orders/',include(('orders.urls','orders'),namespace='orders')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path,re_path

from . import views

urlpatterns = [
    re_path('^$', views.myorders, name='myorders'),
    path('<slug:pk>/', views.OrderDetailView.as_view(), name='orderdetail')

]

products/urls.py
from django.urls import path,re_path

from . import views

urlpatterns = [
    re_path('^$', views.ProductListView.as_view(), name='productlist'),
    path('<slug:pk>/', views.ProductDetailView.as_view(), name='productdetail')
]

orders/models.py
from django.db import models
from carts.models import Cart
import uuid
from django.db.models.signals import pre_save,post_save
import math
from billing.models import BillingProfile
from addresses.models import Address
from django.utils import timezone


ORDER_STATUS_CHOICES=(
    ('created','Created'),
('paid','Paid'),
('shipped','Shipped'),
('refunded','Refunded'),
)

class Order(models.Model):
    billing_profile=models.ForeignKey(BillingProfile,on_delete=models.CASCADE,null=True,blank=True)
    order_id=models.CharField(max_length=200,blank=True)
    shipping_address=models.ForeignKey(Address,related_name='shipping_address',on_delete=models.CASCADE,null=True,blank=True)
    billing_address=models.ForeignKey(Address,related_name='billing_address',on_delete=models.CASCADE,null=True,blank=True)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    status=models.CharField(max_length=120,default='created',choices=ORDER_STATUS_CHOICES)
    shipping_total=models.DecimalField(max_digits=100,decimal_places=2,default=5.99)
    total=models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
    active=models.BooleanField(default=True)
    paid_at = models.DateField(blank=True,null=True)

    def __str__(self):
        return self.order_id

    def update_total(self):
        cart_total=self.cart.total
        shipping_total=self.shipping_total
        newtotal= math.fsum([cart_total,shipping_total])
        formatted_total=format(newtotal,'0.2f')
        self.total=formatted_total
        self.save()
        return newtotal

    def check_done(self):
        billing_profile=self.billing_profile
        shipping_address=self.shipping_address
        billing_address=self.billing_address
        total=self.total
        if billing_profile and shipping_address and billing_address and total>0 :
            return True
        else:
            return False

    def mark_paid(self):
        if self.check_done():
            self.status='paid'
            self.paid_at=timezone.now()
            self.save()
        return self.status

def pre_save_create_order_id(sender,instance,*args,**kwargs):
    if not instance.order_id:
        instance.order_id=uuid.uuid4().hex[:15].upper()
        qs=Order.objects.filter(cart=instance.cart).exclude(billing_profile=instance.billing_profile)
        if qs.exists():
            qs.update(active=False)

pre_save.connect(pre_save_create_order_id,sender=Order)

def post_save_cart_total(sender,instance,created,*args,**kwargs):
    if not created:
        cart_obj=instance
        cart_total=cart_obj.total
        cart_id=cart_obj.id
        qs=Order.objects.filter(cart__id=cart_id)
        if qs.count()==1:
            order_obj=qs.first()
            order_obj.update_total()

post_save.connect(post_save_cart_total,sender=Cart)

def post_save_order(sender,instance,created,*args,**kwargs):
    if created:
        instance.update_total()

post_save.connect(post_save_order,sender=Order)

orders/views.py
from django.shortcuts import render,HttpResponse
from .models import Order
from django.contrib.auth.decorators import login_required
from billing.models import BillingProfile
from django.views.generic.detail import DetailView






@login_required(login_url='/login/')
def myorders(request):
    user=request.user
    billingprofile=BillingProfile.objects.get(user=user)
    user_order=Order.objects.filter(billing_profile=billingprofile,status='paid')
    return render(request,'orders/myorders.html',{'user_orders':user_order})


class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order_details.html'
    def get_context_data(self, **kwargs):
        request=self.request
        context = super().get_context_data(**kwargs)

        return context

templates/orders/myorders.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
{% include 'navbar.html' %}

    <h1>My Orders</h1>
{% if user_orders.count > 0 %}
    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">S.No.</th>
      <th scope="col">Order ID</th>
      <th scope="col">Order Date</th>

    </tr>
  </thead>
  <tbody>
  {% for order in user_orders %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'orders:orderdetail' pk=order.id %}">{{order.order_id}}</a></td>
      <td>{{ order.paid_at }}</td>

    </tr>
  {% endfor %}


  </tbody>
</table>
{% else %}
<p class="lead">No Orders !!</p>
    {% endif %}
{% endblock %}

templates/orders/order_details.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}
    {% include 'navbar.html' %}


                <p><b>Order ID : </b>{{ object.order_id }}</p>

        <p><b>Order Date :</b>{{ object.paid_at }}</p>
                   <p> </p>

    <table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Products</th>
        <th scope="col">Price</th>
    </tr>
    </thead>
    <tbody>
    {% for product in order.cart.products.all %}
        <tr>
        <td><a href="{% url 'products:productdetail' pk=product.id %}">{{ product.title }}</a></td>
        <td>{{ product.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
                <p><b>Shipping Address : </b>{{ object.shipping_address.get_address }}</p>
     <p><b>Billing Address : </b>{{ object.billing_address.get_address }}</p>
    <p><b>Order Total : </b>{{ object.total }}$</p>

    <br>




{% endblock %}